### ISSUE TITLE
Files not pushed.

### ISSUE THREAD

**Issue by sankhadeeproy007** [rnplay/rnplay-cli#5]
Hi, I tried adding my git repo, to rnplay, I successfully added git remote, but when I did "git push rnplay master", it didn't push any files.  "rnplay --open" points to a page where there's an empty index.ios.js file. How do I remove the git remote and redo the process again. Thank you.

**Comment by jsierles** [comment]
Can you give me your app URL?

**Comment by sankhadeeproy007** [comment]
I tried with another repo and it worked. I hadn't pushed .gitignore before. Sorry for the trouble.
