### ISSUE TITLE
git push rnplay master error

### ISSUE THREAD

**Issue by jeangui** [rnplay/rnplay-cli#6]
Hi,

I am trying to use rnplay with git in order to add more files to my rnplay tests.
Nevertheless I have got error when pushing to the master repo:

`D:\SANDBOX\DEVELOPPEMENTS\MOBILE\REACT\SampleApp1>git push rnplay master
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 295 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: fatal: Path '.gitignore' does not exist in 'master'
remote:
remote: Sorry! To prevent problems with conflicting react-native packages, your git repo must not have node_modules checked in. Please add node_modul
 .gitignore and remove any checked-in node_modules.
To https://nhSoCGL44qnPryRPJD86:@git.rnplay.org/WnlhlA.git
   1bef109..fa81217  master -> master`

What am I doing wrong ?
I don't see any node_modules folder in my app directory.

Thanks for the help

Best

Jeangui

**Comment by jeangui** [comment]
Hi,

Sorry. a .gitignore file creation solved the problem.
But I have still a index.ios.js file empty on the rnplay side while it is full on my local machine...
Don't understand.

https://rnplay.org/apps/dhmV2Q

Thanks for help.

Best
jeangui

**Comment by martin-tomasek** [comment]
I have same problem with empty index.ios.js file. When I run "rnplay -c" application is created under my account, but file index.ios.js is empty. I tried it a few times and always create a new application with the same name and an empty file. It seems that my git file was not created (https://pLo3CwdxZDh7tNQy5u5R:@git.rnplay.org/agHBUg.git - 404 - not found).

Here is the complete output:

$ rnplay -c

We found the following project name: AsyncStorage - do you want to use it? y/n
INFO: Setting up new git repo
INFO: Adding git remote
ERROR: Ooops, there has been an error: 
Command failed: /bin/sh -c git remote add rnplay https://pLo3CwdxZDh7tNQy5u5R:@git.rnplay.org/agHBUg.git
fatal: Not a git repository (or any of the parent directories): .git

INFO: If you are sure that you did nothing wrong, please file an issue at the rnplay-cli repo!

**Comment by jsierles** [comment]
I'll take a look at your apps and try to get them fixed. We still don't know why this happens.

Since we're seeing increasing issues with this, we will likely retire this experimental feature from RNPlay.

However, soon we'll be working on a new version of the site which will allow linking repositories directly to the site from Github.

**Comment by jeangui** [comment]
Hi,

It is working fine for me now.

Best 
jeangui

**Comment by martin-tomasek** [comment]
Hello, I have still same problem. 

This command does not work:

$ git remote add rnplay https://pLo3CwdxZDh7tNQy5u5R:@git.rnplay.org/agHBUg.git
fatal: Not a git repository (or any of the parent directories): .git

I try to look at it too. It almost seems that the problem is on my side.

**Comment by jeangui** [comment]
Here is the sequence I use that is working fine:

```
mkdir myProject
cd myProject
rnplay -a
git init
vim .gitignore
vim index.ios.js
git add .gitignore
git add index.ios.js
git commit -m 'sflskjflsfkjs'
rnplay -c
XXXX [same name as the appliction name in the registry]
git push -f rnplay master
```

hope it helps...

**Comment by martin-tomasek** [comment]
Thank you very much. This solved my problem:
git init
git add .gitignore
git add index.ios.js
git commit -m 'test'

I'm sorry, I'm new to React native and command-line git.
